---
# Copyright (C) 2020-2021 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: GPL-2.0-or-later

- name: Preseed values for installation
  debconf:
    name: "sympa"
    question: "{{ item.name | default('sympa') }}/{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.type | default('string') }}"
  with_items:
    - question: "listmaster"
      value: "{% if sympa_listmaster is string %}{{ sympa_listmaster }}{% else %}{{ sympa_listmaster | join(',') }}{% endif %}"
    - question: "hostname"
      value: "{{ sympa_domain }}"
    - name: wwsympa
      question: "wwsympa_url"
      value: "{{ sympa_web_fcgi_protocol }}://{{ sympa_domain }}/{{ sympa_web_path }}"
    - question: "language"
      type: select
      value: "{{ sympa_config_lang }}"
    - question: "remove_spool"
      type: "boolean"
      value: "{{ sympa_debconf_remove_spool | default(false) | ternary('true', 'false') }}"
    - question: "use_soap"
      type: "boolean"
      value: "{{ sympa_soap_fcgi_enabled }}"
  when: ansible_os_family == 'Debian'
  register: ansible_debconf_preseed
  tags:
    - debconf
    - preseed

- name: Ensure that dbconfig is installed
  apt:
    name: dbconfig-common
  when: ansible_os_family == 'Debian'
  tags:
    - debconf
    - dbconfig

- name: Create configuration file for dbconfig
  template:
    src: dbconfig-common.j2
    dest: /etc/dbconfig-common/sympa.conf
    owner: root
    group: root
    mode: 0600
  register: sympa_dbconfig_results
  when: ansible_os_family == 'Debian'
  tags:
    - debconf
    - dbconfig

- name: Install Sympa from distribution package
  package:
    name: sympa
  become: true
  when: sympa_package_file is not defined
  register: sympa_package_distribution_results
  tags:
    - sympa

- name: Create temporary directory for package file
  tempfile:
    state: directory
  register: sympa_tempdir
  when: sympa_package_file is defined
  tags:
    - sympa

- name: Copy package file to target
  copy:
    src: "{{ sympa_package_file }}"
    dest: "{{ sympa_tempdir.path }}/{{ sympa_package_file | basename }}"
    mode: 0644
  when:
    - sympa_package_file is defined
    - sympa_tempdir is not skipped
  tags:
    - sympa

- name: Install Sympa from package file (Debian)
  apt:
    deb: "{{ sympa_tempdir.path }}/{{ sympa_package_file | basename }}"
  when:
    - sympa_package_file is defined
    - sympa_tempdir is not skipped
    - ansible_os_family == 'Debian'
  register: sympa_package_file_results
  tags:
    - sympa

- name: Adjust number of FCGI instances
  lineinfile:
    path: "/etc/default/sympa"
    regexp: "^{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
    create: true
    owner: root
    group: root
    mode: '0644'
  loop:
    - name: WWS_FCGI_CHILDREN
      value: "{{ sympa_web_fcgi_instances }}"
    - name: SOAP_FCGI_CHILDREN
      value: "{{ sympa_soap_fcgi_instances }}"
  notify:
    - restart wwsympa
    - restart sympasoap
  when: ansible_os_family == 'Debian'

- name: Set variable for Sympa command
  set_fact:
    sympa_command: "{{ sympa_package_command }}"
