---
# Copyright (C) 2020-2021 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: GPL-2.0-or-later

- name: Ensures git is installed.
  package:
    name: git
    state: present

- name: Download sources from repository
  git:
    repo: "{{ sympa_repository_url }}"
    dest: "{{ sympa_source_directory }}"
    force: true
    version: "{{ sympa_repository_version }}"
  become_user: "{{ sympa_unix_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: Import tasks to install Perl modules
  import_tasks: perl-modules.yml
