---
# Copyright (C) 2020-2021 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: GPL-2.0-or-later

- name: Create directory for robots
  file:
    state: directory
    path: "{{ sympa_configuration_directory }}/{{ item.domain }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: 0755
  loop: "{{ sympa_robots }}"

- name: Create configuration file
  template:
    src: robot.conf.j2
    dest: "{{ sympa_configuration_directory }}/{{ item.domain }}/robot.conf"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: 0755
  loop: "{{ sympa_robots }}"
  notify:
    - restart sympa
    - restart wwsympa
