---
# Copyright (C) 2020-2021 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: GPL-2.0-or-later

- name: Install FCGI wrapper
  package:
    name: spawn-fcgi
  tags:
    - sympa
    - wwsympa

- name: Create systemd unit for WWSympa
  template:
    src: wwsympa.service.j2
    dest: /etc/systemd/system/wwsympa.service
    owner: root
    group: root
    mode: 0644
  register: wwsympa_unit_file
  notify: restart wwsympa
  tags:
    - sympa
    - wwsympa

- name: Reload systemd if necessary
  systemd:
    daemon_reload: true
  when:
    - wwsympa_unit_file.changed

- name: Ensure that WWSympa is enabled and started
  service:
    name: wwsympa
    enabled: true
    state: started
  tags:
    - sympa
    - wwsympa
